/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import EDD.ListaD;
import EDD.MOrtogonal;
import java.awt.Color;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static mariomaker.Principal.listadoble;

/**
 *
 * @author jenny
 */
public class Comportamiento extends javax.swing.JFrame {
    String comportamiento="";
    //generar nueva form
    //frame en donde se visualiza la matriz    
    JFrame juego;
    JPanel panel;
    MOrtogonal matriz=new MOrtogonal();
    //panel para lista
    JPanel panellista;  
    ListaD listadoble;

    /**
     * Creates new form Comportamiento
     */
    public Comportamiento(ListaD listadoble) {
        initComponents();
        this.listadoble=listadoble;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bPila = new javax.swing.JButton();
        BCola = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        jLabel1.setText("Seleccione el comportamiento ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 270, 30);

        bPila.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        bPila.setText("PILA");
        bPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPilaActionPerformed(evt);
            }
        });
        getContentPane().add(bPila);
        bPila.setBounds(100, 120, 70, 30);

        BCola.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        BCola.setText("COLA");
        BCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BColaActionPerformed(evt);
            }
        });
        getContentPane().add(BCola);
        BCola.setBounds(240, 120, 80, 30);

        bAnterior.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        bAnterior.setText("VOLVER");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(bAnterior);
        bAnterior.setBounds(30, 190, 90, 28);

        bSiguiente.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        bSiguiente.setText("SIGUIENTE");
        bSiguiente.setEnabled(false);
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(bSiguiente);
        bSiguiente.setBounds(280, 190, 110, 28);

        jLabel2.setFont(new java.awt.Font("URW Bookman L", 0, 15)); // NOI18N
        jLabel2.setText("para remover los objetos...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 210, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-240, -80, 720, 410);

        setSize(new java.awt.Dimension(409, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPilaActionPerformed
        // TODO add your handling code here:
        comportamiento="pila";
        bSiguiente.setEnabled(true);
    }//GEN-LAST:event_bPilaActionPerformed

    private void BColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BColaActionPerformed
        // TODO add your handling code here:
        comportamiento="cola";
        bSiguiente.setEnabled(true);
    }//GEN-LAST:event_BColaActionPerformed

    private void GenerarMatriz(){
        
        panel=new JPanel(){
            
            public Dimension getPreferedSize(){
                return new Dimension(500,500);
            }
        };
        JScrollPane jsp=new JScrollPane(panel,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jsp.setBounds(250,150,500,500);        
        juego.add(jsp);
        panel.setLayout(null);
        panel.setBackground(new Color(199,215,250));
        matriz.GenerarMatriz(panel,comportamiento);
        
        
    }
    //genera el panel para visualizar la lista de elementos agregados
    //incluye el comportamiento de salida de los mismos
    private void GenerarLista(){
        int cantidad=listadoble.getCantidad();//cantidad de nodos en la lista
        panellista=new JPanel(){            
            public Dimension getPreferedSize(){
                return new Dimension(500, 50);
            }
        };
        JScrollPane jsp2=new JScrollPane(panellista,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jsp2.setBounds(250, 10, 500,80);
        juego.add(jsp2); 
        panellista.setBackground(new Color(199,215,250));
        //panellista.setLayout(null);
        listadoble.GenerarLista(panellista);  
        
              
              
    }
    //genera nuevo form junto con el panel q contiene la matriz
    private void GenerarForm(){
        juego=new JFrame();
        GenerarMatriz();
        GenerarLista();        
        //fondo frameVista
        juego.setLayout(null);
        URL direccion=null;
        ImageIcon imagen=null; 
        direccion=getClass().getResource("/Imagenes/fondo_1.jpg");
        imagen=new ImageIcon(direccion);
        JLabel fondo=new JLabel(imagen);
        fondo.setBounds(0, 0, 1000, 600);
        juego.add(fondo);
        juego.setLayout(null);
        juego.setSize(1000, 1000);
        juego.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        juego.setLocationRelativeTo(null);
        juego.setVisible(true);                
    }
    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);        
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GenerarForm();
    }//GEN-LAST:event_bSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCola;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bPila;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
